version: 0.2

phases:       
    pre_build:
      commands:
        - npm install      
    build:
      commands:
        - npm run build:ci

artifcats:
  files:
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.ico'
  base-directory: 'dist/picsapp'
    