version: 0.2

phases:       
    pre_build:
      commands:
        - npm install      
    build:
      commands:
        - npm run build:ci

artifacts:
    files:
        - '**/*.html'
        - '**/*.js'
        - '**/*.css'
        - '**/*.ico'
        - '**/*.svg'
        - '**/*.eot'
        - '**/*.ttf'
        - '**/*.woff'
        - '**/*.woff2'
    discard-paths: yes
    base-directory: 'dist/picsapp*'
    